# Generated by Django 4.0.2 on 2022-02-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostar',
            field=models.BooleanField(default=True),
        ),
    ]
