# Generated by Django 4.0.2 on 2022-02-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mostar',
            new_name='mostrar',
        ),
    ]
